### ISSUE TITLE
[FEATURE REQUEST] Delete actor linked to token if polymorphed

### ISSUE THREAD

**Issue by zdaar** [VanceCole/player-token-permissions#1]
Adding an option to delete the actor linked to the token would allow players to both polymorph and cancel their own polymorph.
For now, whenever an player polymorph backs into their own token the temporary actor created through polymorph stays in the actors list. Each instance of player-initiated polymorph reversion leaves the temporary actor.

Goes like this with the core foundry polymorph system :
- Druid polymorphs by drag and drop a bear token on their sheet.
- Temporary actor is created called Druid (Brown Bear)
- Druid token is replaced by Druid (Brown Bear) actor token

Then when reversing the polymorph by clicking the Reverse Transformation on the Druid (Brown bear) token: 
If a GM does it :
- The Druid (Brown bear) token gets deleted and replaced by the Druid token
- The Druid (Brown bear) actor gets deleted
If a player does it : 
- The Druid (Brown bear) token gets deleted and replaced by the Druid token 
- The Druid (Brown bear) actor does not get deleted.

If a played polymorphs multiple times it will keep creating Druid (Brown bear) tokens.

If your module had an option to delete the token's linked actor maybe with an Are you sure prompt and/or a check to see if the actor has the polymorphed flag - which must exist since these tokens have a special top bar menu entry to Revert transformation, indicating the state is tracked - , we could truly make use of the "Allow players to polymorph their own tokens" option.

**Comment by VanceCole** [comment]
Hi Zdaar,

Thank you for the suggestion, it is definitely an annoyance if you use the polymorph feature a lot, however I consider this out of scope for Player Token Permissions due to the following:
- Polymorph acts on entity type `Actor`
- Polymorph is a dnd5e system feature

While Player Token Permissions is
- Intended only to expand permissions of entity type `Token`
- System agnostic

A separate module could address this of course, I took a brief look at the situation and there is no hook emitted when restoring transformation so an implementation would need to patch the restore function and emit it's own event. For the latter half of the problem you could easily use PTP as an example how to accomplish the event transmission.

Regards,

-Vance
